name:                wolfram
version:             0.1.0.0
synopsis:            "Wolfram Automaton Simulator"
description:         "A simple Haskell program to simulate Wolfram's automaton."
homepage:            https://github.com/githubuser/Wolfram#readme
license:             BSD-3-Clause
author:              Clément Bouret
maintainer:          clement.bouret@epitech.eu
copyright:           2025 Clément Bouret
category:            Simulation
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  wolfram:
    main: Main.hs
    source-dirs: src
    dependencies:
      - base

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
